### ISSUE TITLE
Locus breaker bis can output multiple loci and thus can not be used as it is to redefine region

### ISSUE THREAD

**Issue by SoCadiou** [ht-diva/pqtl_pipeline_finemap#18]
locus breaker bis is used to redefine region according to conditional pvalues. More precisely, it is meant to exclude from a conditional dataset the parts of the locus near to the borders which do not countain any conditional pvalues lower than a specific threshold. This is done using locus breaker function.
However, depending on the size of the locus and the pvalues thresholds used, in some cases, locus breaker bis can divide the locus in multiple loci. In this case, only the new locus corresponding to the top snp should be taken into account to define the new borders. Currently only the new locus having the earlier start site is taken into account. This lead to spurious filtering and some conditional datasets not containing the corresponding independant snp.
This should be solved by adding in the script:
- testing if the output of the second call of locus breaker ("new_bounds") has multiple rows
- if yes, keeping only the row with the top snp having the lowest conditonal pvalue (highest mlog10pC)
- then use new_bounds as it is currently used to redefine borders

**Comment by dariushghasemi** [comment]
To address the issue provoked by Solene, we added a line at the end of locus breaker BIS part in the script to take the most significant conditional SNP using `top_n(mlog10pC, n=1)` if the locus got broken into multiple loci.
