### ISSUE TITLE
clean up the locus breaker script

### ISSUE THREAD

**Issue by clagiamba** [ht-diva/pqtl_pipeline_finemap#9]
We don't need the full container with all the packages for locus breaker, we only need these two packages:
suppressMessages(library(data.table))
suppressMessages(library(tidyverse))

Also, we need to produce a "completed.flag" file reporting the seqids that have run so that we know if a seqid was run but no significant locus was found. e.g. /group/diangelantonio/users/claudia/OneDrive/BELIEVE/locus_breaker/claudia/final/sequential/s03_locus_breaker.R if that helps. 

One more: please add the final merging and in a second step the filtering of MHC region, and if possible add two options depending on which genome build the GWAS is in.

**Comment by dariushghasemi** [comment]
The required packages are specified and listed in two YAML files in the under `workflow/envs` subdirectories.
